// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestAutomationTemplate.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Google Search")]
    public partial class GoogleSearchFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GoogleSearch.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Google Search", "In order to to find new information\r\nI will google the following terms\r\nBecause I" +
                    " want to be a genius", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search Google")]
        [NUnit.Framework.CategoryAttribute("FunctionalUI")]
        [NUnit.Framework.TestCaseAttribute("IPhone4SLandscape", "Barney Loves me", null)]
        [NUnit.Framework.TestCaseAttribute("IPhone4SPortrait", "Hello World!!", null)]
        [NUnit.Framework.TestCaseAttribute("IPhone5SLandscape", "This is text", null)]
        [NUnit.Framework.TestCaseAttribute("IPhone5SPortrait", "This is a demo", null)]
        [NUnit.Framework.TestCaseAttribute("IPadLandscape", "These searches are logged to my google account", null)]
        [NUnit.Framework.TestCaseAttribute("IPadPortrait", "The world is ending", null)]
        [NUnit.Framework.TestCaseAttribute("SamsungS3MiniLandscape", "Hello", null)]
        [NUnit.Framework.TestCaseAttribute("SamsungS3MiniPortrait", "Bye", null)]
        [NUnit.Framework.TestCaseAttribute("SamsungS4Landscape", "Software Developer", null)]
        [NUnit.Framework.TestCaseAttribute("SamsungS4Portrait", "Windows 98", null)]
        [NUnit.Framework.TestCaseAttribute("NokiaLumia610Landscape", "Open Box Software", null)]
        [NUnit.Framework.TestCaseAttribute("NokiaLumia610Portrait", "StackoverFlow", null)]
        [NUnit.Framework.TestCaseAttribute("WindowsSurfaceProLandscape", "I am silly", null)]
        [NUnit.Framework.TestCaseAttribute("WindowsSurfaceProPortrait", "Do we really need to do this", null)]
        [NUnit.Framework.TestCaseAttribute("MotorolaXoomLandscape", "There is meaning to life", null)]
        [NUnit.Framework.TestCaseAttribute("MotorolaXoomPortrait", "There is no meaning to cats on the internet", null)]
        public virtual void SearchGoogle(string device, string searchTerm, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "FunctionalUI"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search Google", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given(string.Format("I am using the follwing \'{0}\'", device), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And(string.Format("I have searched for \'{0}\'", searchTerm), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.Then("search results should be returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
