namespace ExampleMVPApplication.Models
{
    /// <summary>
    /// Exchange Rate Entity, this would come as the entity generated by your chosen ORM
    /// </summary>
    public class ExchangeRate
    {
        /// <summary>
        /// Gets or sets the exchange rate identifier.
        /// </summary>
        /// <value>
        /// The exchange rate identifier.
        /// </value>
        public int ExchangeRateId { get; set; }

        /// <summary>
        /// Gets or sets the period.
        /// </summary>
        /// <value>
        /// The period.
        /// </value>
        public int Period { get; set; }

        /// <summary>
        /// Gets or sets the _ currency code.
        /// </summary>
        /// <value>
        /// The _ currency code.
        /// </value>
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or sets the _ rate.
        /// </summary>
        /// <value>
        /// The _ rate.
        /// </value>
        public decimal Rate { get; set; }

        /// <summary>
        /// Gets or sets the _ version.
        /// </summary>
        /// <value>
        /// The _ version.
        /// </value>
        public byte[] Version { get; set; }

        /// <summary>
        /// Gets or sets the _ inserted date.
        /// </summary>
        /// <value>
        /// The _ inserted date.
        /// </value>
        public System.DateTime _InsertedDate { get; set; }

        /// <summary>
        /// Gets or sets the _ updated date.
        /// </summary>
        /// <value>
        /// The _ updated date.
        /// </value>
        public System.DateTime _UpdatedDate { get; set; }

        /// <summary>
        /// Gets or sets the _ updated by staff identifier.
        /// </summary>
        /// <value>
        /// The _ updated by staff identifier.
        /// </value>
        public int _UpdatedByStaffId { get; set; }
    }
}
